### PR TITLE
centos 6.6 VM with Python 2.6.6

### PR DESCRIPTION
**Pull request by chrisheaththomas**
To stop us using python 2.7 dependencies!

### CODE REVIEW

**Comment by edwinbka** [comment]
@chrisheaththomas After this change, will it still be the same command , vagrant up to start the VM ?
Just wanted to understand if anything else had changed apart from the OS .

**Comment by chrisheaththomas** [comment]
@edwinbka yes command will remain the same `vagrant up`. If you previously created the Ubuntu VM you will have to do one off command `vagrant destroy` first.

I realised over the weekend that I need to replace the Ubuntu dependent commands in the provision.sh script with the equivalent RHEL ones before this pull request can be merged.

**Comment by chrisheaththomas** [comment]
Ready to review and consider for merge.

**Comment by chrisheaththomas** [comment]
Clean test performed. (Followed README steps, followed by DB connection test:

     $ python

    >>>import cx_Oracle
    >>>con = cx_Oracle.connect('<user>/<psswd>@<ip>/<service_name>')
    >>>print con.version
    >>>con.close()

Followed by running unit tests for B_EXSPDBEB batch.

**Pull request merged**
